name: check formatting
on:
  release:
    types: [published]

jobs:
  trigger-bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          repository: funes-data/sparse-checkout 
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          path: sparse-checkout

      - uses: ./sparse-checkout 
        with:
          repository: funes-data/vtools
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          patterns: actions
          path: ghca 

      - name: Trigger Versions Bump Buildkite Job
        uses: ./ghca/actions/buildkite-pipeline-trigger
        with:
          buildkite_token: ${{ secrets.BUILDKITE_TOKEN }}
          buildkite_org: funes
          buildkite_pipeline: ${{ vars.CLOUD_PIPELINE }}
          commit: HEAD
          branch: ${{ vars.CLOUD_DEFAULT_BRANCH }}
          message: Install Pack version bump trigger
          env: '{"INSTALLPACK_BUMP": "1", "RELEASE_VERSION": "${{ github.ref_name }}"}'
